[build]
  publish = "netlify_public"
  command = "npm run netlify:build"

[build.environment]
  NODE_VERSION = "18"

# Handle routing for static site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 